[[navbar]]
    identifier = "decoracions"
    name = "Decoracións"
    url = "/decoracions/"
    weight = 1
[[navbar]]
    identifier = "festas"
    name = "Celebracións"
    url = "/festas/"
    weight = 2
    [[navbar]]
        parent = "festas"
        identifier = "cumples"
        name = "Cumpleanos"
        url = "/festas/cumpleanos/"
        weight = 1
    [[navbar]]
        parent = "festas"
        identifier = "aniversarios"
        name = "Aniversarios"
        url = "/festas/aniversarios/"
        weight = 2
    [[navbar]]
        parent = "festas"
        identifier = "sanva"
        name = "San Valentín"
        url = "/festas/sam-vai-lentin/"
        weight = 3
    [[navbar]]
        parent = "festas"
        identifier = "pascua"
        name = "Pascua"
        url = "/festas/pascua/"
        weight = 4
    [[navbar]]
        parent = "festas"
        identifier = "nai"
        name = "Día da Nai"
        url = "/festas/dia-nai/"
        weight = 5
    [[navbar]]
        parent = "festas"
        identifier = "pai"
        name = "Día da Pai"
        url = "/festas/dia-pai/"
        weight = 6
[[navbar]]
    identifier = "contacto"
    name = "Contacto"
    url = "/contacto/"
    weight = 6
[[navbar]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre/"
    weight = 7

